import type { AttributeHandleCallback, AttributeType } from './models';
export declare const attributeCallbacks: Record<AttributeType, AttributeHandleCallback>;
export declare const attributeTypes: AttributeType[];
export declare const attributeTypesLength: number;
export declare const controllerAttribute = "data-controller";
export declare const actionAttributePattern: RegExp;
export declare const extendedActionAttributePattern: RegExp;
export declare const targetAttributePattern: RegExp;
export declare const changeEventTypes: Set<string>;
export declare const defaultEvents: Record<string, string>;
export declare const ignoredInputTypes: Set<string>;
export declare const parseableInputTypes: Set<string>;
